### ISSUE TITLE
How use as shortcut

### ISSUE THREAD

**Issue by KaduAmaral** [zzjin/syncViewScroll#4]
How to use command as shortcut? I try `{ "keys": ["ctrl+k", "ctrl+s"], "command": "syncscroll" }`, but doesn't work.

**Comment by zzjin** [comment]
the correct command is "toggle_sync_scroll"
please try :
`{ "keys": ["ctrl+k", "ctrl+s"], "command": "toggle_sync_scroll" }`

**Comment by KaduAmaral** [comment]
Still not... :/

**Comment by zzjin** [comment]
@KaduAmaral sry, I've update readme show how to do this thx.
https://github.com/zzjin/syncViewScroll/blob/master/ReadMe.md

**Comment by KaduAmaral** [comment]
Yeah, now works @zzjin. Hey, can I suggest something... When toggle sync, do for both tabs in evidence, now I have to do this 2 times, once for each. :/

Anyway, thanks for fix. :D
