### ISSUE TITLE
disabled item in menu?

### ISSUE THREAD

**Issue by getify** [zzjin/syncViewScroll#9]
Just installed in ST2. "Sync Scroll" Item is disabled in View menu. Is this known (since the support for ST2 is fuzzy)? Or is there something else I'm missing?

Can't activate it with a keyboard shortcut either, it seems.

**Comment by CSester** [comment]
Same here (linux).

Additionally, on startup:
``` Python
Reloading plugin /home/admin/.config/sublime-text-2/Packages/Sync View Scroll/syncscroll.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./syncscroll.py", line 3, in <module>
    import _thread as thread
ImportError: No module named _thread
```
